logging:
  level:
    org:
      hibernate:
        SQL: debug
spring:
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    default: des
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true
project:
  jwt:
    signKey: Bu:GW8bgPlEw
    expirationMinutes: 1440

---
spring:
  datasource:
    url: @dataSourceDes.url@
    username: @dataSourceDes.user@
    password: @dataSourceDes.password@
  devtools:
    restart:
      trigger-file: reload
    livereload:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  config:
    activate:
      on-profile: des

---
spring:
  datasource:
    url: @dataSourcePro.url@
    username: @dataSourcePro.user@
    password: @dataSourcePro.password@
  devtools:
    add-properties: false
  config:
    activate:
      on-profile: pro